### ISSUE TITLE
Upgrade to new version of Tilt

### ISSUE THREAD

**Issue by fleetio** [trvsdnn/frank#57] opened 2011-09-28 14:34 UTC
Frank currently specifies gem version 0.9 of Tilt, but the current release of Tilt is 1.3.3. Any particular reason for this?

The reason I ask is that Tilt 0.9 doesn't work with the current version of the Less gem, so compiling Less templates effectively doesn't work in Frank right now...

**Comment by trvsdnn** [comment] 2011-09-28 18:13
It would probably require a few things to get frank working with 1.3.3, but i'll take a look when I get a chance. You're more than welcome to give it a go.

**Comment by fleetio** [comment] 2011-09-28 21:03
I'll upgrade and see how far I can get. May have to get your thoughts on any errors I come across. Will let you know.

Thanks.

**Comment by edrex** [comment] 2011-09-28 21:55
Just stumbled on this issue looking for info on using less with Frank.

Possible to put an old version of the less gem in Frank's Gemfile? What version?

**Comment by fleetio** [comment] 2011-09-28 22:00
I actually tried that by installing LESS v1.2.21 (`gem install less -v 1.2.21`) but still ran into more issues. Can't remember exactly what the problem was, but it didn't seem to be the quick fix I was hoping for...

**Comment by trvsdnn** [comment] 2011-09-29 16:28
I should have some time this weekend to take a look at it. I for sure want to get everything working with the most recent version of tilt... no reason people should have to hack it up to get less going.

**Comment by trvsdnn** [comment] 2011-10-01 01:42
Pushed a new version with updated tilt dependency. I couldn't reproduce any issues with less. I tested with both 1.8.7 and 1.9.2.

Try `1.0.9` and see if it works. Closing for now.

**Closed as completed by trvsdnn** 2011-10-01 01:42 UTC

**Comment by fleetio** [comment] 2011-10-02 17:32
Thanks @blahed.

I can compile `.less` files fine now in Frank, however the less compiler is choking whenever I try to `@import` another `.less` file. Tried all sorts of directory combinations but didn't have any luck.

Seems to be a problem with the Less Ruby gem and not Frank though. I'll keep trying and will post back if I figure out anything, but I may just start using this app to process Less files in the background: http://incident57.com/less/

**Comment by trvsdnn** [comment] 2011-10-03 18:44
Haven't tried this. Will check it out tonight.

**Comment by edrex** [comment] 2011-10-12 17:37
Just dove in with this. It seems like `@import` should pick up files relative to the current less file, but it doesn't. Does seem to be a problem with the less gem.

@rarestep: as a workaround I put the following in my setup.rb

``` ruby
require 'tilt'
require 'less'


class LessTemplate < Tilt::LessTemplate
  def prepare
    if ::Less.const_defined? :Engine
      @engine = ::Less::Engine.new(data)
    else
      options = @options.merge(:paths => [
        File.join(File.dirname(__FILE__), '/dynamic/css'),
        File.join(File.dirname(__FILE__), '/dynamic/css/bootstrap')
      ])
      parser  = ::Less::Parser.new(options.merge :filename => eval_file, :line => line)
      @engine = parser.parse(data)
    end
  end
end
Tilt.register 'less', LessTemplate
```

**Comment by edrex** [comment] 2011-10-26 21:08
Note that the less gem segfaults my frank server process frequently but YMMV. Seems like an alternate that uses the lessc binary would be cool. For now, I have a `build.sh` script like this:

``` bash
BASE=$PWD

rm -rf $BASE/build

cd static/less
  lessc site.less > $BASE/static/css/site.css
cd $BASE
frank export --production build
```
